In [5]:
#LABEL and ORDINAL ENCODER in scikit learn

#if the given data set is having the categorical data then convert it into  the numerical data
"""
Nominal data-->In the data set the output variable is categorical like(T/F) then the (LABEL Encoder) is used to convert 0 or 1.

In the input features  the categories are in order( Low, Medium, High	) then (ORDINAL Encoder) is used.

if catogeries are not in order like (names),(fruits-->apple,banana,etc) are not in order then (ONE HOT ENCODER) is used.

"""
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/CAR DETAILS FROM CAR DEKHO.csv')
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [4]:
df.drop('name',axis=1,inplace=True)
df

year  selling_price  km_driven    fuel seller_type transmission  \
0     2007          60000      70000  Petrol  Individual       Manual   
1     2007         135000      50000  Petrol  Individual       Manual   
2     2012         600000     100000  Diesel  Individual       Manual   
3     2017         250000      46000  Petrol  Individual       Manual   
4     2014         450000     141000  Diesel  Individual       Manual   
...    ...            ...        ...     ...         ...          ...   
4335  2014         409999      80000  Diesel  Individual       Manual   
4336  2014         409999      80000  Diesel  Individual       Manual   
4337  2009         110000      83000  Petrol  Individual       Manual   
4338  2016         865000      90000  Diesel  Individual       Manual   
4339  2016         225000      40000  Petrol  Individual       Manual   

             owner  
0      First Owner  
1      First Owner  
2      First Owner  
3      First Owner  
4     Second Owner  
...            ...  
4335  Second Owner  
4336  Second Owner  
4337  Second Owner  
4338   First Owner  
4339   First Owner  

[4340 rows x 7 columns]

In [9]:


"""
df['transmission'].map({'manual':0,'Automatic':1})
df['seller'].map({'individual':0,'dealer':1,'trustmark dealer':2})

#same thing we can do in python also
df['transmission'].apply(lambda x: 1 if x=='manual'else 0 )

"""
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_text=train_test_split(df.drop('fuel',axis=1),df['fuel'],test_size=0.2,random_state=42)

x_train.shape

(3472, 6)

In [10]:
x_test.shape

(868, 6)

In [13]:
#converting the data into values in table by LABEL encoder

from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

le=LabelEncoder()
y_train_scaled=le.fit_transform(y_train)
y_test_scaled=le.fit_transform(y_text)#this will give 0,1,2,.... to distinct names in column

y_train_scaled  # gives output as numpy array


array([1, 1, 4, ..., 1, 1, 4])

In [12]:
y_test_scaled

array([1, 3, 3, 1, 1, 3, 3, 3, 1, 3, 1, 1, 1, 1, 3, 3, 1, 1, 3, 1, 1, 1,
       3, 1, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1, 3, 1, 1, 3, 3, 3, 1, 3, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, 1, 3, 1, 3, 3,
       3, 3, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 3,
       3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3, 1, 3, 1, 1, 3, 1, 1, 3, 1, 3, 1,
       2, 3, 1, 3, 3, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 3, 3, 1, 1,
       1, 3, 3, 1, 1, 3, 3, 3, 3, 3, 1, 3, 1, 3, 1, 1, 1, 1, 3, 0, 1, 3,
       1, 3, 1, 3, 3, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 3, 3, 3, 1, 1,
       3, 1, 3, 1, 1, 1, 1, 3, 3, 1, 3, 1, 3, 1, 1, 3, 1, 3, 3, 3, 1, 3,
       1, 3, 3, 1, 1, 1, 3, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 3, 3,
       1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 1, 3,
       1, 3, 3, 1, 1, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 3,
       1, 1, 1, 3, 3, 3, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 1,

In [17]:

#OrdinalEncoder

de=OrdinalEncoder()
x_train_scaled=de.fit_transform(x_train)
x_test_scaled=de.fit_transform(x_test)

x_train_scaled


array([[ 23., 350., 114.,   1.,   1.,   0.],
       [ 24., 187., 294.,   1.,   1.,   0.],
       [ 19.,  33., 141.,   1.,   1.,   2.],
       ...,
       [ 22., 229., 298.,   0.,   1.,   0.],
       [ 19., 101., 453.,   1.,   1.,   0.],
       [ 19.,  69., 453.,   1.,   1.,   0.]])

In [15]:
x_test_scaled

array([[ 14.,  42., 189.,   1.,   1.,   0.],
       [ 23.,  66.,  63.,   1.,   1.,   0.],
       [ 12.,  29.,  98.,   1.,   1.,   2.],
       ...,
       [ 15.,  38.,  91.,   1.,   1.,   2.],
       [ 21., 150.,  10.,   2.,   1.,   0.],
       [ 23., 135.,  73.,   0.,   1.,   0.]])